language: node_js
node_js:
- node
- --lts # LTS: See https://github.com/creationix/nvm/pull/1070
branches:
  only:
  - dev
install:
  - npm install
script:
  - npm run build
after_success:
  - sh build/deploy.sh
